### ISSUE TITLE
Import aragon-apps and aragon-core as submodules to keep documentation in code repos

### ISSUE THREAD

**Issue by izqui** [aragon/aragon-wiki#100]
Instead of duplicating the documentation in the repos and wiki, we could have all documentation in the relevant repos and then import the repos as a submodule in the wiki and link the docs in the `mkdocs.yml`.

This will allow for code repos to have awesome documentation that also gets shown in the wiki.

**Comment by sohkai** [comment]
Closing; we will keep app documentation in their repos as READMEs.
