### ISSUE TITLE
Analytics

### ISSUE THREAD

**Issue by izqui** [aragon/aragon-wiki#112]
I know there will be a bit of controversy around this issue, but I think analytics are specially important in the wiki, to know what documents are read more, in order to polish them and do more content on similar issues.

I'm sure we can do this in a privacy preserving way without selling our community to Google, but in this case I think it is pretty hard to improve without stats.

PS: We could also add feedback buttons at the end of each page: 'How useful was this document in a scale from Ethereum to Tron?' And we could have ppl click directly in the crypto logo lol.

**Comment by Smokyish** [comment]
Looks like Piwik has re-branded to [Matomo](https://github.com/matomo-org/matomo), but since it has built-in privacy features, i would see that as probably the best option for the analytics.

**Comment by Smokyish** [comment]
Closed in 5b1ca6e111ee1c45e34fef861c3fd23b4c277d75
