### ISSUE TITLE
Rename AragonOS -> aragonOS everywhere 

### ISSUE THREAD

**Issue by izqui** [aragon/aragon-wiki#119]
In today's dev meeting the entire dev team unanimously agreed on the new capitalization to be used for aragonOS. 

We need to update both in the wiki and medium posts

**Comment by Smokyish** [comment]
@izqui Duplicate issue to https://github.com/aragon/aragon-wiki/issues/115

Closed in https://github.com/aragon/aragon-wiki/commit/28a75711df15f893f7c4137ebe090d672050d266

**Comment by Smokyish** [comment]
@izqui So this includes all mentions of aragonOS outside the `aragon/aragonOS` repo?

**Comment by izqui** [comment]
Yes
