### ISSUE TITLE
De-duplicate "Presentations" subsection

### ISSUE THREAD

**Issue by john-light** [aragon/aragon-wiki#124]
There is currently a `Documentation > Presentations` section and a `Videos > Presentations` section. I propose we keep the Videos subsection and delete the Documentation subsection.

**Comment by Smokyish** [comment]
It is under Documentation as well because that's where the slides/PDF's aka documentation of the presentations are hosted.

**Comment by john-light** [comment]
Ok I'll leave it be then :)
