### ISSUE TITLE
Add a Write-Up for January 2018 - Alexa

### ISSUE THREAD

**Issue by Smokyish** [aragon/aragon-wiki#140]
Team members will produce a write-up of the most important things they have worked on since last Community Meeting, the problems they have found and what they plan to do in the next weeks (that can be a bit blurry, and that's fine). These write-ups will be published as a blog post for the community to review on Monday before Friday's meeting.

Create your own Write-Up for Community Meeting 06 using the same structure as https://raw.githubusercontent.com/aragon/aragon-wiki/master/docs/meetings/community/write-ups/cm06/tatu.md

**Must be submitted by end of day, Thursday 1st of February 2018!**

**Comment by alexarwr** [comment]
Operations:
- Organized and Booked Q1 Team Offsite
- Worked on finding payment service providers 
- Met with our new law firm to set up payment in ETH and ANT
- Sent final reports from December to our accountants to close out FY2017
- Making payments to service providers, ordering equipment for the team, paying conference sponsorships and community awards and lots of small details like that.
- January Payroll 

Next:
- Work with our accountants to finalize and audit FY2017 reporting
- Help get payroll application and automated payment to Lawyers off the ground
- Start on Q2 Offsite
- Work on finalizing logistics for Q1 Events/Meetups/Conferences
