### ISSUE TITLE
Update 2018 blog index

### ISSUE THREAD

**Issue by Smokyish** [aragon/aragon-wiki#144]
Currently missing two latest posts, [Launch of Aragon Nest](https://blog.aragon.one/launch-of-aragon-nest-8d42d1a37595) and [Introducing aragonOS 3.0 alpha, the new operating system for protocols and DApps](https://blog.aragon.one/introducing-aragonos-3-0-alpha-the-new-operating-system-for-protocols-and-dapps-348f7ac92cff).

**Comment by john-light** [comment]
Thanks for the reminder, fixing now! During future blog post prep can you please assign "Add to wiki blog index" as a task to me for each post so this does not fall through the cracks again?

**Comment by Smokyish** [comment]
@john-light I have now updated the Publishing process with the additional subtask of updating blog index.
