### ISSUE TITLE
Update ACL function names

### ISSUE THREAD

**Issue by yjkimjunior** [aragon/aragon-wiki#187]
This update needs to follow once PR #226 in AragonOS get merged.

createPermission(...) -> create(...)
_createPermission(...) -> _create(...)
grantPermission(...) -> grant(...)
grantPermissionP(...) -> grantP(...) or grantWithParams(...)
revokePermission(...) -> revoke(...)
_setPermission(...) -> _set(...)
setPermissionManager(...) -> setManager(...)

**Comment by sohkai** [comment]
Closing; we have not updated these function names in aragonOS.
