### ISSUE TITLE
Add a Write-Up for March 2018 - Alexa

### ISSUE THREAD

**Issue by Smokyish** [aragon/aragon-wiki#197]
Team members will produce a write-up of the most important things they have worked on since last Community Meeting, the problems they have found and what they plan to do in the next weeks (that can be a bit blurry, and that's fine). These write-ups will be published as a blog post for the community to review on Monday before the Community Meeting.

Create your own Write-Up for Community Meeting 10 using the same structure as https://raw.githubusercontent.com/aragon/aragon-wiki/master/docs/meetings/community/write-ups/cm06/tatu.md

Must be submitted by end of day, Sunday 1st of April 2018!

**Comment by alexarwr** [comment]
March 2018
**Accounting and Ops**
Planning Q2 Offsite
Multi-Sig Transparency reporting
Assisting with Luis with legal
Making payments to service providers, travel arrangements for the team, paying conference sponsorships, and lots of small details like that
Financial Reporting March 2018 
Payroll
**Next**
Q3 Planning: Logistics for lots of Events/Meetups/Conferences
Helping to make sure Payroll gets automated
