### ISSUE TITLE
Add a Write-Up for March 2018 - Chris

### ISSUE THREAD

**Issue by Smokyish** [aragon/aragon-wiki#200]
Team members will produce a write-up of the most important things they have worked on since last Community Meeting, the problems they have found and what they plan to do in the next weeks (that can be a bit blurry, and that's fine). These write-ups will be published as a blog post for the community to review on Monday before the Community Meeting.

Create your own Write-Up for Community Meeting 10 using the same structure as https://raw.githubusercontent.com/aragon/aragon-wiki/master/docs/meetings/community/write-ups/cm06/tatu.md

Must be submitted by end of day, Sunday 1st of April 2018!

**Comment by chris-remus** [comment]
Chris - Product Manager

#### Complete Onboarding
- Provide feedback on and input to Team Handbook
- Provide input for team interview blog post
- Complete initial 1-on-1 conversations with team members

#### Draft Product Management Process
- Draft overall product management process flow diagram
- Share diagram with team for input

#### Initiate regular 1on1 Conversations w/Dev and Design Team Members
- Jorge
- Bingen
- Brett
- Jouni
- Oliver
- Pierre

#### Support 0.5 Release
- Monthly update call
- Q&A with their team

### Next

#### Develop 0.5 Feedback Collection Process
- Determine how to collect feedback from internal and external channels
- Determine how to process feedback for input into dev process

#### Refine Product Development Process
- Update with team feedback
- Begin adding implementation specific detail

#### Begin Supporting Nest
- Review proposals as requested
- Begin thinking about relationship between Nest development and internal development processes

#### Continue Regular 1on1 Conversations with Dev and Design Teams

**Comment by chris-remus** [comment]
Need to update current text to -

**Complete Onboarding**

- Attend onboarding week in Madrid to work with Jorge and Luis
- Provide feedback on and input to Team Handbook
- Provide input for team interview blog post
- Complete initial 1-on-1 conversations with team members

**Refine Product Development Process**

- Update with team feedback
- Begin adding implementation specific detail
