### ISSUE TITLE
Add a Write-Up for April 2018 - Alexa

### ISSUE THREAD

**Issue by Smokyish** [aragon/aragon-wiki#243]
Team members will produce a write-up of the most important things they have worked on since last Community Meeting, the problems they have found and what they plan to do in the next weeks (that can be a bit blurry, and that's fine). These write-ups will be published as a blog post for the community to review on Monday before the Community Meeting.

Create your own Write-Up for Community Meeting 10 using the same structure as https://raw.githubusercontent.com/aragon/aragon-wiki/master/docs/meetings/community/write-ups/cm06/tatu.md

*Must be submitted by end of day, Tuesday 1st of May 2018!*

**Comment by alexarwr** [comment]
### Alexa - Operations

#### Accounting and Ops
- Offsite #2 in Switzerland
- Multi-Sig Transparency reporting
- Assisting with Luis with legal
- Making payments to service providers, travel arrangements for the team, paying conference sponsorships, and lots of small details like that
- Financial Reporting March-April 2018
- Payroll

### Next
- Logistics for Events/Meetups/Conferences
- Automating Payroll
- Offsite #3 Planning

#### Events:
- EdCon (May 3-5th, Toronto)
- CoinCenter Annual Dinner (May 14th, NYC)
- ETHBuenosAires (May 25-27th, Buenos Aires)
