### ISSUE TITLE
Add Althea and The Planning Tab

### ISSUE THREAD

**Issue by luisivan** [aragon/aragon-wiki#274]
Althea announced they will use Aragon, and obviously The Planning Tab too. Can we add them to the wiki? Also with the mockups
![althea](https://user-images.githubusercontent.com/718208/40041934-f8830f7c-581f-11e8-8ec9-9935aa00826c.jpg)
![planning](https://user-images.githubusercontent.com/718208/40041936-f9c9c704-581f-11e8-8dd5-7f4b4330c25b.jpg)

**Comment by Smokyish** [comment]
Closed in https://github.com/aragon/aragon-wiki/commit/db0bc036e48811d88eb080f613a9d5ee2dc146eb
