### ISSUE TITLE
"Aragon core" -> "Aragon Core"

### ISSUE THREAD

**Issue by john-light** [aragon/aragon-wiki#34]
This is more a question right now than a suggestion. Is the software called "Aragon core" or "Aragon Core"? In the navigation menu for the Wiki, it is called "Aragon core".

**Comment by Smokyish** [comment]
@john-light That is a reference to the [aragon/aragon-core](https://github.com/aragon/aragon-core) repo that houses the Aragon app smart contracts, it just happens to be named similarly...

**Comment by john-light** [comment]
@Smokyish might we consider renaming to prevent confusion?

**Comment by john-light** [comment]
@Smokyish should I close this issue given the `wontfix` label?

**Comment by Smokyish** [comment]
@izqui Thoughts on this? Should we rename the repo or just keep it as it is? Renaming the app itself probably would be too much at this point.

**Comment by izqui** [comment]
We started calling the app 'Aragon Core' to differentiate from the 'Aragon Network'. IMO, the client should be called just 'Aragon' and keep `aragon-core` as they are the core contracts that power Aragon. Regardless of this, I have been considering merging all smart contract related stuff to a repo called `aragon-contracts`, but undecided yet.

**Comment by john-light** [comment]
@izqui per our discussion on Keybase, we decided that the best course of action would be to change the name of the `aragon-core` repo to `aragon-os`. I will open a new issue here for renaming throughout the wiki and open an issue in the `aragon-core` repo to change the name to `aragon-os`.
