### ISSUE TITLE
Add links to social profiles and community discussion forums

### ISSUE THREAD

**Issue by john-light** [aragon/aragon-wiki#38]
Unsure where this should go exactly, but I think it'd be good to have somewhere. Maybe on the Home page?  

**Rocket Chat**  
https://aragon.chat  

**Reddit**  
https://www.reddit.com/r/aragonproject/

**Twitter**  
https://twitter.com/aragonproject  

**LinkedIn**  
https://www.linkedin.com/company/aragonproject/

**YouTube**  
https://www.youtube.com/c/AragonProject

**Comment by Smokyish** [comment]
@john-light The social media links are already in the footer of every page except Aragon Chat, so only that needs to be added.
