### ISSUE TITLE
Reorganize security disclosures section

### ISSUE THREAD

**Issue by sohkai** [aragon/aragon-wiki#477]
Right now, the security reporting guidelines are coupled with the documentation for the bug bounty.

We should re-organize this to separate them, so the security reporting guidelines are more clear for security researchers.

**Comment by john-light** [comment]
@sohkai  what do you think about implementing https://securitytxt.org/ ?

**Comment by sohkai** [comment]
That would also be a great idea, we should definitely expose something like this on aragon.org! [The footer link can even just point to this](https://github.com/aragon/website/issues/101)!
