### ISSUE TITLE
"Bug bounty" page has no styling

### ISSUE THREAD

**Issue by onbjerg** [aragon/aragon-wiki#503]
Clicking "Bug bounty" in the footer of the forums sends you to this page that has no styling at all: https://wiki.aragon.org/dev/bug_bounty/

Edit: although the footer issue specifically should be fixed, this issue tracks the general problem that dead links to not look pretty on our wiki

![Screenshot_2019-10-01 Aragon Wiki](https://user-images.githubusercontent.com/9424721/65963024-2d514080-e45a-11e9-81cc-8830014ce926.png)

**Comment by sohkai** [comment]
@john-light Ah, we need to change the footer of the website + other places to use the new location: https://wiki.aragon.org/dev/security/bug_bounty/

**Comment by john-light** [comment]
Yes although there is currently a re-organization PR that will change the location of the Bug Bounty file again, I think this is important enough that we should update the current link ASAP. I have created an issue for this in the website repo here: https://github.com/aragon/website/issues/104

**Comment by antonyip** [comment]
#434 I've fixed this before, seems like it was added back..

**Comment by sohkai** [comment]
Ah interesting, thanks for the notice @antonyip! This must've got caught in our redesign; let's re-apply that change 😅.
