### ISSUE TITLE
Wiki is borked 🐛

### ISSUE THREAD

**Issue by burrrata** [aragon/aragon-wiki#506]
Firefox on Ubuntu19

Worked a few days ago. Went to the wiki yesterday it looked like this. Today I also went to the wiki and it's still borked so reporting this bug. Looks like it might be a deployment snafu, but I dunno
 
![1](https://user-images.githubusercontent.com/42473928/65368592-3435b300-dc11-11e9-97dd-eea40362e526.png)
![2](https://user-images.githubusercontent.com/42473928/65368593-3566e000-dc11-11e9-9fc0-e9f2e4ccfcc8.png)
![3](https://user-images.githubusercontent.com/42473928/65368596-3b5cc100-dc11-11e9-9d09-3aea37c1f81b.png)
![4](https://user-images.githubusercontent.com/42473928/65368594-3861d080-dc11-11e9-8826-16dbddde9a04.png)

**Comment by john-light** [comment]
That's usually what it looks like when you're on a page that doesn't exist anymore. Try just going to https://wiki.aragon.org and navigating from there.
