### ISSUE TITLE
Images show up broken

### ISSUE THREAD

**Issue by john-light** [aragon/aragon-wiki#508]
Some images are showing up broken on the Wiki website, even though on GitHub they look fine. 

e.g. https://wiki.aragon.org/media/press/press-kit/#brand-guidelines

**website**

![Screenshot_2019-10-01 Press Kit - Aragon Wiki](https://user-images.githubusercontent.com/9424721/65962889-eb27ff00-e459-11e9-8113-7f440c445303.png)

**GitHub**

![Screenshot_2019-10-01 aragon aragon-wiki](https://user-images.githubusercontent.com/9424721/65962878-e7947800-e459-11e9-9b93-a556f33bc1d5.png)

**Comment by sohkai** [comment]
@john-light @delfipolito The image links for these are using the wrong URL paths.

For example, `https://wiki.aragon.org/media/design/logo/jpg/imagetype_dark.jpg` should be `https://wiki.aragon.org/design/logo/jpg/imagetype_dark.jpg` on that page.
