### ISSUE TITLE
Update Blog Table of Contents to have alternating colors in titles

### ISSUE THREAD

**Issue by john-light** [aragon/aragon-wiki#6]
Purpose: Improve visibility and readability

**Comment by Smokyish** [comment]
Update extra.css so that the right side navbar `Table of Contents` has alternating colors in titles, alternating with the current black and light grey.

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0x59db48eba01144597ae0eca47f85c6953494e9635281cd7c8da9cfb6320514d2](https://etherscan.io/tx/0x59db48eba01144597ae0eca47f85c6953494e9635281cd7c8da9cfb6320514d2)

**Comment by adipurnama83** [comment]
0xa1719da09b61c6d1fe0b1254b7e5374904e03cc2
