### ISSUE TITLE
Create artwork for Aragon

### ISSUE THREAD

**Issue by Smokyish** [aragon/aragon-wiki#77]
We need multiple resources, from Powered by Aragon icons to graphic resources to be used in blog posts etc.

Reference: http://wiki.aragon.one/design/

**Comment by DeividSaenz** [comment]
Hello, @Smokyish 

I'm a designer/illustrator and would be happy to contribute. Let me know specifically what you need and I can see how I arrange my times to help :)

**Comment by Smokyish** [comment]
@DeividSaenz Hi, we now have the [Artwork](https://wiki.aragon.one/design/artwork/) page up on the wiki, so any additions to that are most welcome!

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0x5e18f55a7b1ac10516ab0ca35bd8f0f2add9a48ebb1e9b483cefb8643730c2b7](https://etherscan.io/tx/0x5e18f55a7b1ac10516ab0ca35bd8f0f2add9a48ebb1e9b483cefb8643730c2b7)

**Comment by elioqoshi** [comment]
Would love to help on this! Checking out the wiki

**Comment by elioqoshi** [comment]
@Smokyish What do you think about these?
![image](https://user-images.githubusercontent.com/5436686/35530816-75c95a1a-0535-11e8-95e5-02187747cf33.png)

**Comment by elioqoshi** [comment]
I also added the resources to Identihub, self hosted software which I have worked on the past year:
https://demo.identihub.co/project/aragon

It's completely open source and the idea is to allow people to self host it and/or have all data kept independently. code is on GitHub: 
https://github.com/uracreative/identihub

**Comment by Smokyish** [comment]
@elioqoshi Those look great, thank you!

Could you create a new Pull Request that adds the SVG and PNG versions to `docs/design/artwork/powered_by/` (a new folder as it doesn't exist yet) and having `Closes #77` in the description.

> To claim this bounty sign up at https://openbounty.status.im and make sure to update your Ethereum address in My Payment Details so that the bounty is correctly allocated.

Be sure to also sign up and add your Ethereum address in the link above to claim the 10 ANT bounty on this!

**Comment by elioqoshi** [comment]
Thanks @Smokyish! Should be good to go. Also have my address already on Status.
