### ISSUE TITLE
Create a page for the Transparency Model

### ISSUE THREAD

**Issue by john-light** [aragon/aragon-wiki#79]
I did not see a link anywhere on the website or the wiki. I had to go back to the blog post announcement to find it.

**Comment by Smokyish** [comment]
Changing the scope of this.

Let's create a documentation page for the whole [Transparency Model](https://blog.aragon.one/why-transparency-matters-d6f9e6e10985#91bf) and thus the link to the [transparency page](http://transparency.aragon.one/) will get included and it's possible for us to update the model in the future if need be.

**Comment by yermoo** [comment]
is it possible collaboration with us 
http://transparency.aragon.one/#/
How could I do it selflessly?
Thank you
