### ISSUE TITLE
Translate AragonOS doc to Spanish

### ISSUE THREAD

**Issue by izqui** [aragon/aragon-wiki#87]
https://wiki.aragon.one/dev/AragonOS/

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0xe7e974ad9ee7804d3c27990cd5c2c8f5dd9c2ab77c86e9eed48dbedcd4567d7f](https://etherscan.io/tx/0xe7e974ad9ee7804d3c27990cd5c2c8f5dd9c2ab77c86e9eed48dbedcd4567d7f)

**Comment by alejodosr** [comment]
Hi izqui, I am interested in translating this document. It's amazing to contribute to this amazing project (small contribution, but still :) ). Thanks.

**Comment by izqui** [comment]
Awesome! You can ask questions on https://aragon.chat

**Comment by alejodosr** [comment]
Nice! I am working on it..

**Comment by izqui** [comment]
@alejodosr Just a heads up, there is a PR making some grammatical fixes to this document that will get merged soon: #95

**Comment by alejodosr** [comment]
Ok @izqui I'll check it out, Is it planned to be merged soon? (in days timeframe :) )

**Comment by izqui** [comment]
Sweet, here is a little guide on how to submit it after you are done :) https://github.com/aragon/aragon-wiki/issues/88#issuecomment-354943359

**Comment by alejodosr** [comment]
Ok, I am finishing the translation based on [f2e09d4](https://github.com/aragon/aragon-wiki/commit/f2e09d4c135046bd496315ec14bb26d6dfaf765c?short_path=4b2b2d8#diff-4b2b2d803d6ba34a3124884c38588dc5)

**Comment by Chumalaka** [comment]
Hi Izqui, can I still contribute?

**Comment by alejodosr** [comment]
@izqui, I am finishing the document :) and I am about to do the PR. Only a few notes:

- I am not touching the code specification, which I guess it shouldn't be translated. Am I correct?
- I am translating words like "Kernel", which I replace by "Núcleo". What is your policy regarding these cases?

**Comment by izqui** [comment]
@Chumalaka looks like @alejodosr is close to finishing. We will do more bounties in the future tho!

> I am not touching the code specification, which I guess it shouldn't be translated. Am I correct?
Correct

> I am translating words like "Kernel", which I replace by "Núcleo". What is your policy regarding these cases?

That's fine! Specifically 'kernel', I think it would be useful to use kernel directly too, as it is a pretty standard computer world that almost everyone reading the document will be familiar with

**Comment by alejodosr** [comment]
Ok, I am submitting the PR right now. In the end I have taken into account both commits in #95

**Comment by alejodosr** [comment]
PR submitted! @izqui let me know if you need further modifications. Thanks!

**Comment by izqui** [comment]
Perfect! will review soon as it is quite an undertaking :)
