### ISSUE TITLE
Translate DevPlan to Spanish

### ISSUE THREAD

**Issue by izqui** [aragon/aragon-wiki#88]
https://wiki.aragon.one/documentation/Development_Plan/

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0xd2597d616ba84898bd16bbe632b0029987dea9adea774274d00ef7c0259a3c22](https://etherscan.io/tx/0xd2597d616ba84898bd16bbe632b0029987dea9adea774274d00ef7c0259a3c22)

**Comment by DeividSaenz** [comment]
Hello. I want to contribute. I have the translation to spanish ready, but I'm a newbie to the openbounties. Should I upload the document here?

**Comment by DeividSaenz** [comment]
Here's de translation in .docx format. Not sure if this is the right way to proceed, though. Any help for a newbie?

[DevPlan-SpanishTranslation.docx](https://github.com/aragon/aragon-wiki/files/1599017/DevPlan-SpanishTranslation.docx)

**Comment by izqui** [comment]
Thanks for taking the time @DeividSaenz, looking good! Happy to help make your contribution merged :)

Go to the `translations/spanish` directory and click `create new file`:

<img width="1020" alt="2018-01-03 at 7 07 25 am" src="https://user-images.githubusercontent.com/447328/34510522-d5d2e2be-f054-11e7-8eba-5a1b95e93166.png">

It will require you to fork `aragon-wiki` at some point. 

Name the new file `devplan.md` and the formatting have to be in [Markdown](https://daringfireball.net/projects/markdown/), for reference, this is how the English version of the document is formatted: https://raw.githubusercontent.com/aragon/aragon-wiki/master/docs/documentation/Development_Plan.md

Along the way, you can click preview to see how it will look. After you are done editing, submit a pull request. Once it is reviewed and merged, you can get the bounty!

**Comment by DeividSaenz** [comment]
Thanks @izqui ! Now I believe I did it right. Let me know if anything :)
