### ISSUE TITLE
Translate App reference to Spanish

### ISSUE THREAD

**Issue by izqui** [aragon/aragon-wiki#89]
https://wiki.aragon.one/dev/apps/

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0x843a378d0a3b34470d13cf7e8cecedde0f39b0785cf91af72ee7e4379457f2e8](https://etherscan.io/tx/0x843a378d0a3b34470d13cf7e8cecedde0f39b0785cf91af72ee7e4379457f2e8)

**Comment by linuxchip** [comment]
Hi izqui, i am interested to work on this. Thanks

**Comment by izqui** [comment]
Awesome! There is sort of a guide here: https://github.com/aragon/aragon-wiki/pull/86/files#diff-cf45117b30f35c87b6d2995a9fb438b5

**Comment by linuxchip** [comment]
Any specific time line you guys are looking for this ?

**Comment by izqui** [comment]
Not really, but regarding the bounty, there is no such thing as a 'reserved' issue (though signaling you are working on it is good). First PR merged gets the bounty :)

**Comment by linuxchip** [comment]
Sounds good. I can start working on this. I am commenting here so that other people don't waste their time here ;-)

**Comment by Chumalaka** [comment]
Hi Izqui, can I still contribute?

**Comment by linuxchip** [comment]
Just an update, 80% of the work is completed.
I will complete it soon. Thanks

**Comment by linuxchip** [comment]
@izqui , i completed translating and raised pull request.

Thanks for giving me this oppurtunity

**Comment by jeamick** [comment]
The goal is to have it just in Spanish but also in  other languages ( French for example) ?

**Comment by bachellerieloic** [comment]
Where do I start. I speak English, Spanish, French.

**Comment by linuxchip** [comment]
@izqui , can you please check on this ? Thanks

**Comment by samvaldez** [comment]
I'm interested in work on this!

**Comment by luisivan** [comment]
Doens't seem like we can have documentation up to date, so we will defer this until we have the bandwidth
